In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from mpl_toolkits.mplot3d import Axes3D

# res = [0, 0, 0]
# while res[0] != 9 or res[1] != 9 or res[2] != 9:
#   colors = np.random.randint(0, 255, (27, 3))
#   kmeans = KMeans(n_clusters=3)
#   kmeans.fit(colors)
#   labels = kmeans.predict(colors)
#   res = [np.sum(labels == i) for i in range(3)]
#   # fig = plt.figure()
#   # ax = fig.add_subplot(111, projection='3d')
#   # for i in range(3):
#   #   ax.scatter(colors[labels == i, 0], colors[labels == i, 1], colors[labels == i, 2], label="Cluster {}".format(i))
#   # plt.title("1000 Random Colors Clustered into 10 Clusters")
#   # plt.xlabel("Red")
#   # plt.ylabel("Green")
#   # # plt.zlabel("Blue")
#   # plt.legend()
#   # plt.show()

In [2]:
main_colors = [[225, 171, 214],
        [ 96, 123, 152],
        [120, 175, 174],
        [217,  40, 177],
        [135, 113,  80],
        [ 14, 110, 164],
        [122, 206, 183],
        [200, 227,  36],
        [155,  89, 108],
        [ 59,  62,  89],
        [115, 161,  47],
        [225, 102, 179],
        [  1, 188,  76],
        [ 82, 254, 126],
        [246, 111, 171],
        [132, 113, 204],
        [184,  15,  64],
        [175,  15, 180],
        [235, 142, 191],
        [164,  11, 120],
        [177, 118,  55],
        [  3, 174, 216],
        [162, 115, 223],
        [204, 211, 208],
        [ 60, 168,  75],
        [174, 140,  35],
        [  7,  22, 217]]
main_labels = [1, 0, 0, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0, 1, 1, 0, 2, 0]

In [132]:
np.save('main_colors', main_colors, allow_pickle=True)
np.save('main_color_labels', main_labels, allow_pickle=True)

In [134]:
main_labels = np.load('main_color_labels.npy')
main_labels

array([1, 0, 0, 1, 2, 0, 0, 2, 2, 2, 2, 1, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0,
       1, 1, 0, 2, 0])

In [5]:
def rgb_to_hex(r, g, b):
  # Convert the RGB components to hexadecimal values.
  r_hex = hex(r)[2:].zfill(2)
  g_hex = hex(g)[2:].zfill(2)
  b_hex = hex(b)[2:].zfill(2)

  # Return the hexadecimal color.
  return '{}{}{}'.format(r_hex, g_hex, b_hex)

# Example usage
sharp_colors = []
for c in main_colors:
    hx = rgb_to_hex(c[0], c[1], c[2])
    sharp_colors.append(hx)
    print(hx)

e1abd6
607b98
78afae
d928b1
877150
0e6ea4
7aceb7
c8e324
9b596c
3b3e59
73a12f
e166b3
01bc4c
52fe7e
f66fab
8471cc
b80f40
af0fb4
eb8ebf
a40b78
b17637
03aed8
a273df
ccd3d0
3ca84b
ae8c23
0716d9


In [8]:
main_labels = np.array(main_labels)
zero = np.where(main_labels == 0)[0]
one = np.where(main_labels == 1)[0]
two = np.where(main_labels == 2)[0]

In [10]:
np.array(sharp_colors)[zero]

array(['607b98', '78afae', '0e6ea4', '7aceb7', '01bc4c', '52fe7e',
       '03aed8', '3ca84b', '0716d9'], dtype='<U6')

In [11]:
np.array(sharp_colors)[one]

array(['e1abd6', 'd928b1', 'e166b3', 'f66fab', '8471cc', 'af0fb4',
       'eb8ebf', 'a273df', 'ccd3d0'], dtype='<U6')

In [12]:
np.array(sharp_colors)[two]

array(['877150', 'c8e324', '9b596c', '3b3e59', '73a12f', 'b80f40',
       'a40b78', 'b17637', 'ae8c23'], dtype='<U6')

In [40]:
# test_color = np.random.randint(0, 255, (1, 3))[0]
test_color = [10, 24, 145]
c = test_color
sharp_test_color = rgb_to_hex(c[0], c[1], c[2])
sharp_test_color

'0a1891'

In [15]:
def softmax(x):
  exp_x = np.exp(x)
  sum_exp_x = np.sum(exp_x)
  return exp_x / sum_exp_x

In [156]:
# ! pip install colour
from colour import Color
red = Color("red")
spectrum_colors = list(red.range_to(Color("green"),9))
   
# colors is now a list of length 10
# Containing: 
# [<Color red>, <Color #f13600>, <Color #e36500>, <Color #d58e00>, <Color #c7b000>, <Color #a4b800>, <Color #72aa00>, <Color #459c00>, <Color #208e00>, <Color green>]

In [154]:
colors = list(red.range_to(Color('green'), 200))

In [157]:
spectrum_colors

[<Color red>,
 <Color #ef3c00>,
 <Color #df7000>,
 <Color #cf9c00>,
 <Color #bfbf00>,
 <Color #84b000>,
 <Color #50a000>,
 <Color #249000>,
 <Color green>]

In [74]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.preprocessing import MinMaxScaler

dists = euclidean_distances([test_color], main_colors)[0]
sims = cosine_similarity([test_color], main_colors)[0]
# np.array(main_colors)[zero]

In [80]:
# softmax(sims[zero])
def min_max_normalize(data):
  # Calculate the minimum and maximum values in the dataset.
  min_val = data.min()
  max_val = data.max()

  # Subtract the minimum value from each value and then divide by the difference between the maximum and minimum values.
  normalized_data = (data - min_val) / (max_val - min_val)

  return normalized_data

In [100]:
sims[zero]

array([0.80875584, 0.75771651, 0.91072967, 0.73659735, 0.52027768,
       0.57925576, 0.86941579, 0.54396105, 0.99737957])

In [101]:
sims[one]

array([0.71588607, 0.69100846, 0.68206891, 0.63568377, 0.85146155,
       0.7614352 , 0.67895092, 0.83449954, 0.70320311])

In [102]:
sims[two]

array([0.54980209, 0.28225114, 0.62886622, 0.82372254, 0.39486091,
       0.39884221, 0.64389954, 0.38856399, 0.30554828])

In [134]:
# zero_softmax = []
# zero_responses = (np.random.randint(0, 100, (1, 9)) / 100)[0]
# for i in range(9):
#     sign = np.random.randint(2)
#     if sign:
#         zero_softmax.append(sims[zero][i] + 0.4 * zero_responses[i])
#     else:
#         zero_softmax.append(sims[zero][i] - 0.4 * zero_responses[i])
zero_softmax = softmax(zero_softmax)

In [135]:
# one_softmax = []
# one_responses = (np.random.randint(0, 100, (1, 9)) / 100)[0]
# for i in range(9):
#     sign = np.random.randint(2)
#     if sign:
#         one_softmax.append(sims[one][i] + 0.4 * one_responses[i])
#     else:
#         one_softmax.append(sims[one][i] - 0.4 * one_responses[i])
one_softmax = softmax(one_softmax)

In [136]:
# two_softmax = []
# two_responses = (np.random.randint(0, 100, (1, 9)) / 100)[0]
# for i in range(9):
#     sign = np.random.randint(2)
#     if sign:
#         two_softmax.append(sims[two][i] + 0.4 * two_responses[i])
#     else:
#         two_softmax.append(sims[two][i] - 0.4 * two_responses[i])
two_softmax = softmax(two_softmax)

In [145]:
for z in zero_softmax:
    print(colors[int(z*1000)])

print('--------')
for o in one_softmax:
    print(colors[int(o*1000)])
    
print('--------')
for t in two_softmax:
    print(colors[int(t*1000)])

#c4b500
#64a600
#99b600
#c1bc00
#d48f00
#c7ae00
#caa900
#85b000
#0b8500
--------
#cba700
#a5b900
#cda100
#c0be00
#c0bf00
#66a700
#cba700
#439b00
#4d9f00
--------
#9cb600
#c2ba00
#c2bb00
#279100
#b2bc00
#afbb00
#8bb200
#9eb700
#d09b00


In [152]:
for z in min_max_normalize(sims)[zero]:
    print(colors[np.min([199, int(z*1000) // 5])])

print('--------')
for o in min_max_normalize(sims)[one]:
    print(colors[np.min([199, int(o*1000) // 5])])
    
print('--------')
for t in min_max_normalize(sims)[two]:
    print(colors[np.min([199, int(t*1000) // 5])])

#54a100
#73ab00
#238f00
#7eae00
#d58d00
#caa900
#359600
#d09900
green
--------
#8bb200
#9cb600
#a3b800
#c0be00
#3e9a00
#6fa900
#a5b900
#479d00
#95b400
--------
#d09b00
red
#c2bb00
#4d9f00
#eb4900
#eb4b00
#bcbf00
#ec4500
#fb0f00
